version: "3.8"

services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "5000:5000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - processed:/app/processed

  worker:
    build: .
    command: npx ts-node-dev src/worker.ts
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - uploads:/app/uploads
      - processed:/app/processed

volumes:
  uploads:
  processed: